spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ulutman
    username: ulutmanuser
    password: localpassword


jwt:
  secret: localdevsecretkey_at_least_32_characters_long_for_hs256

minio:
  url: https://fly.storage.tigris.dev
  access-key: your_aws_access_key_id
  secret-key: your_aws_secret_access_key
  bucket: ulutman-images
  region: auto
